;(function(){
    var Form=window.Form=function(){
        this.user=document.getElementById("user");
        this.userspan=document.getElementById("userspan");
        this.verify=document.getElementById("verify");
        this.verifyspan=document.getElementById("verifyspan");
        this.pass1=document.getElementById("pass1");
        this.pass1span=document.getElementById("pass1span");
        this.pass2=document.getElementById("pass2");
        this.pass2span=document.getElementById("pass2span");
        this.checkbox=document.getElementById("checkbox");
        this.checkboxspan=document.getElementById("checkboxspan");
        this.sub=document.getElementById("sub");
        this.subspan=document.getElementById("subspan");
        this.cover=document.getElementById("cover");
        this.random=document.getElementById("random");
        this.operator=document.getElementById("operator");
        this.num1=document.getElementById("num1");
        this.num2=document.getElementById("num2");
        this.a=0;
        this.b=0;
        this.c=0;
        this.d=0;
        this.e=0;
        this.registerarr=[];
        this.render();
        this.road();
        this.bindEvent();
    }
    Form.prototype.render=function(){
        var operatorarr=["+","-","*"];
        this.num1.innerHTML=parseInt(Math.random()*10);
        this.num2.innerHTML=parseInt(Math.random()*10);
        this.operator.innerHTML=operatorarr[parseInt(Math.random()*3)];
    }
    Form.prototype.road=function(){
        this.registerarr=JSON.parse(localStorage.getItem("register"))||[];
    }
    Form.prototype.bindEvent=function(){
        var that=this;
        this.user.onblur=function(){
            var reguser=/^1[0-9]{10}$/;
            if(reguser.test(this.value)){
                if(that.registerarr.length<1){
                    that.a=1;
                    that.cover.style.display="none";
                    that.userspan.innerHTML="此手机号可用";
                    that.userspan.style.color="green";
                }else{
                    for(var i=0;i<that.registerarr.length;i++){
                        if(this.value==that.registerarr[i]["user"]){
                            that.a=0;
                            that.cover.style.display="block";
                            that.userspan.innerHTML="该手机号已被注册，请重新输入";
                            that.userspan.style.color="red";
                            return;
                        }
                    }
                    that.a=1;
                    that.cover.style.display="none";
                    that.userspan.innerHTML="此手机号可用";
                    that.userspan.style.color="green";
                }
            }else{
                that.a=0;
                that.cover.style.display="block";
                that.userspan.innerHTML="请输入正确的手机号";
                that.userspan.style.color="red";
            }
        }
        this.random.onclick=function(){
           that.render();
        }
        this.verify.onblur=function(){
            switch (that.operator.innerHTML) {
                case "+":
                    that.jieguo=parseInt(that.num1.innerHTML)+parseInt(that.num2.innerHTML);
                    break;
                case "-":
                    that.jieguo=that.num1.innerHTML-that.num2.innerHTML;
                    break;
                case "*":
                    that.jieguo=that.num1.innerHTML*that.num2.innerHTML;
                default:
                    break;
            }
            if(this.value==that.jieguo){
                that.verifyspan.innerHTML="输入正确";
                that.verifyspan.style.color="green";
                that.b=1;
            }else{
                that.verifyspan.innerHTML="计算错误，请重新计算";
                that.verifyspan.style.color="red";
                that.b=0;
            }
        }
        this.pass1.onblur=function(){
            var regpass=/^[a-zA-Z_0-9]{6,20}$/;
            if(regpass.test(this.value)){
                that.pass1span.innerHTML="输入正确"
                that.pass1span.style.color="green";
                that.c=1;
            }else{
                that.pass1span.innerHTML="输入错误，请输入正确的6~20位数由字母、数字、“_”的组合的密码"
                that.pass1span.style.color="red";
                that.c=0;
            }
        }
        this.pass2.onblur=function(){
            if(that.c==0){
                that.pass2span.innerHTML="请先输入正确的密码"
                that.pass2span.style.color="red";
                that.d=0;
            }else{
                if(that.pass1.value==this.value){
                    that.pass2span.innerHTML="输入正确"
                    that.pass2span.style.color="green";
                    that.d=1;
                }else{
                    that.pass2span.innerHTML="两次输入不一致，请重新输入"
                    that.pass2span.style.color="red";
                    that.d=0;
                }
            }
        }
        this.checkbox.onclick=function(){
            if(this.checked){
                that.e=1;
                that.checkboxspan.innerHTML="";
            }else{
                that.e=0;
                that.checkboxspan.innerHTML="请先阅读协议，并同意";
            }
        }
        this.sub.onclick=function(){
            if(that.e==0){
                that.checkboxspan.innerHTML="请先阅读协议，并同意";
            }
            if(that.a+that.b+that.c+that.e+that.d==5){
                that.subspan.innerHTML="恭喜你注册成功";
                that.subspan.style.color="green";
                that.verify.value="";
                that.registerarr.push({"user":that.user.value,"pass":that.pass1.value})
                localStorage.setItem("register",JSON.stringify(that.registerarr));
                that.render();
            }else{
                that.subspan.innerHTML="请先完成上述步骤";
                that.subspan.style.color="red";
            }
        }
    }
})();